language: node_js
node_js: "4"

sudo: required
dist: trusty
branches:
  only:
    - master

before_install:
  - cd ..
  - git clone --depth=50 --branch=master https://github.com/seisman/seisman.info.git seisman.info
  - cd seisman.info
  - git submodule update --init --recursive --remote

install:
  # install the latest version of pandoc
  - curl -s https://api.github.com/repos/jgm/pandoc/releases/latest | grep 'browser_download_url.*deb' | awk '{print "wget", $2}' | sh
  - sudo dpkg -i pandoc-*-amd64.deb
  - npm install hexo gulp -g
  - npm install

script:
  - hexo generate --silent
  - gulp

after_success:
  - git config --global user.name "Dongdong Tian"
  - git config --global user.email "seisman.info@gmail.com"

  # deploy to coding.net
  - cd public
  - git init && git add . && git commit -m "pages for coding"
  - git push -u -f "https://${CODING_USER}:${CODING_PASSWD}@${CODING_URL}" master:${CODING_BRANCH}
  - cd ..

  # deploy to github.com
  - hexo clean
  - sed -i 's!//cdn.bootcss.com/.*.js$!!' themes/next/_config.yml
  - sed -i 's!//cdn.bootcss.com/.*.css$!!' themes/next/_config.yml
  - sed -i 's!http://o7l077v4h.bkt.clouddn.com/!!' themes/next/_config.yml
  - sed -i 's/- .\/pandoc-filters.js//' _config.yml
  - sed -i 's!http://7j1zxm.com1.z0.glb.clouddn.com/!!' themes/next/_config.yml
  - hexo generate --silent
  - gulp
  - cd public
  - git init && git add . && git commit -m "pages for github"
  - git push -u -f "https://${GH_TOKEN}@github.com/seisman/seisman.info.git" master:gh-pages
